<a href="https://colab.research.google.com/github/MinhTuan76800310/Machine-Learning-and-Deep-Learning/blob/main/TensorFlow_Tensors_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import library

In [281]:
import tensorflow as tf
import numpy as np

Create random number in range

In [282]:
tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))

tf.Tensor([4 3 1], shape=(3,), dtype=int32)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)
tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor([1 3 3], shape=(3,), dtype=int32)


In [283]:
tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))

tf.Tensor([4 3 1], shape=(3,), dtype=int32)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)
tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor([1 3 3], shape=(3,), dtype=int32)


Constant

In [284]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [285]:
tensor_bool = tf.constant([True,True,False])
print(tensor_bool)

tf.Tensor([ True  True False], shape=(3,), dtype=bool)


In [286]:
tensor_string = tf.constant(["hello world","hi "])
print(tensor_string)

tf.Tensor([b'hello world' b'hi '], shape=(2,), dtype=string)


Casting

In [287]:
tensor_one_d = tf.constant([2,0.,-3,8,90],dtype=tf.float32)
casted_tensor_one_d = tf.cast(tensor_one_d,dtype=tf.bool)
print(tensor_one_d)
print(casted_tensor_one_d)

tf.Tensor([ 2.  0. -3.  8. 90.], shape=(5,), dtype=float32)
tf.Tensor([ True False  True  True  True], shape=(5,), dtype=bool)


Create array n dimension

In [288]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [289]:
tensor_three_d = tf.constant([
    [[1,2,0],
    [3,5,-1]],

    [[10,2,0],
    [1,0,2]],

    [[5,8,0],
    [2,7,0]],

    [[2,1,9],
    [4,-3,32]],

])
print(tensor_three_d)

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)


In [290]:
print(tensor_three_d.ndim)

3


In [291]:
print(tensor_three_d.shape)

(4, 2, 3)


In [292]:
t = tf.constant([[1, 1, 1], [2, 2, 2]],)
tf.size(t,out_type=tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

In [293]:
# shape of tensor 't' is [2, 2, 3]
t = tf.constant([[1, 1, 1], [2, 2, 2]])
tf.rank(t)  # 3

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [294]:
print(tf.shape(tensor_three_d))

tf.Tensor([4 2 3], shape=(3,), dtype=int32)


In [295]:
tensor_four_d = tf.constant([

[
    [[1,2,0],
    [3,5,-1]],

    [[10,2,0],
    [1,0,2]],

    [[5,8,0],
    [2,7,0]],

    [[2,1,9],
    [4,-3,32]],

],

[
    [[13,26,0],
    [3,5,-12]],

    [[10,2,0],
    [1,0,23]],

    [[5,8,0],
    [2,73,0]],

    [[2,1,9],
    [4,-30,32]],

],

[
    [[103,26,0],
    [3,50,-12]],

    [[100,2,0],
    [1,0,23]],

    [[5,28,0],
    [2,3,0]],

    [[22,1,9],
    [44,-320,32]],

],

])
print(tensor_four_d)

tf.Tensor(
[[[[   1    2    0]
   [   3    5   -1]]

  [[  10    2    0]
   [   1    0    2]]

  [[   5    8    0]
   [   2    7    0]]

  [[   2    1    9]
   [   4   -3   32]]]


 [[[  13   26    0]
   [   3    5  -12]]

  [[  10    2    0]
   [   1    0   23]]

  [[   5    8    0]
   [   2   73    0]]

  [[   2    1    9]
   [   4  -30   32]]]


 [[[ 103   26    0]
   [   3   50  -12]]

  [[ 100    2    0]
   [   1    0   23]]

  [[   5   28    0]
   [   2    3    0]]

  [[  22    1    9]
   [  44 -320   32]]]], shape=(3, 4, 2, 3), dtype=int32)


In [296]:
import numpy as np

In [297]:
np_array = np.array([1,2,4])
print(np_array)

[1 2 4]


In [298]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 4], shape=(3,), dtype=int64)


In [299]:
eye_tensor = tf.eye(
    num_rows=5,
    num_columns=None,
    batch_shape=[2,4],
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]


 [[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]], shape=(2, 4, 5, 5), dtype=float32)


In [300]:
fill_tensor = tf.fill(
    [1,3,4],5, name=None
)
print(fill_tensor)

tf.Tensor(
[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]], shape=(1, 3, 4), dtype=int32)


In [301]:
zeros_tensor = tf.zeros(
    [3,2],
    dtype=tf.dtypes.float32,
    name=None
)
print(zeros_tensor)

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [302]:
ones_tensor = tf.ones(
    [3,2],
    dtype=tf.dtypes.float32,
    name=None
)
print(ones_tensor)

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [303]:
ones_like_tensor = tf.ones_like(fill_tensor)
print(ones_like_tensor)

tf.Tensor(
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]], shape=(1, 3, 4), dtype=int32)


In [304]:
random_tensor = tf.random.normal(
    [3,2],
    mean=100.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[ 99.819695  99.04971 ]
 [ 99.96036   99.25746 ]
 [101.32315   99.381454]], shape=(3, 2), dtype=float32)


In [305]:
random_tensor = tf.random.uniform(
    [5,5],
    minval=0,
    maxval=1000,
    dtype=tf.dtypes.int32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[597 764 960 558  70]
 [817 340 143 777 334]
 [632 429 283 664 894]
 [120 292 511 585 171]
 [601 294 650 406 833]], shape=(5, 5), dtype=int32)


In [306]:
import tensorflow as tf
import numpy as np

In [307]:
tensor_zero_d = tf.constant(1)
print(tensor_zero_d)

tf.Tensor(1, shape=(), dtype=int32)


In [308]:
tensor_one_d = tf.constant([3,0,3], dtype = tf.float32)
print(tensor_one_d)

casted_tensor_one_d = tf.cast(tensor_one_d, dtype = tf.uint16)
print(casted_tensor_one_d)

tf.Tensor([3. 0. 3.], shape=(3,), dtype=float32)
tf.Tensor([3 0 3], shape=(3,), dtype=uint16)


In [309]:
tensor_two_d = tf.constant([[1,2,0],
                            [3,5,-1],
                            [1,5,6],
                            [2,3,8]])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [310]:
tensor_three_d = tf.constant([[[1,2,0],
                             [3,5,-1]],

                            [[10,2,0],
                             [1,0,2]],

                            [[5,8,0],
                             [2,7,0]],

                            [[2,1,9],
                             [4,-3,32]]])
print(tensor_three_d.ndim)

3


In [311]:
tensor_four_d = tf.constant([[[[1,2,0],
                             [3,5,-1]],

                            [[10,2,0],
                             [1,0,2]],

                            [[5,8,0],
                             [2,7,0]],

                            [[2,1,9],
                             [4,-3,32]]],



                             [[[0,2,5],
                             [5,3,1]],

                            [[0,2,0],
                             [-1,10,0]],

                            [[0,5,1],
                             [1,7,0]],

                            [[3,8,7],
                             [2,3,2]]],



                             [[[4,5,4],
                             [3,1,1]],

                            [[0,2,5],
                             [0,4,3]],

                            [[3,2,4],
                             [5,8,3]],

                            [[8,2,5],
                             [2,3,3]]]])
print(tensor_four_d)

tf.Tensor(
[[[[ 1  2  0]
   [ 3  5 -1]]

  [[10  2  0]
   [ 1  0  2]]

  [[ 5  8  0]
   [ 2  7  0]]

  [[ 2  1  9]
   [ 4 -3 32]]]


 [[[ 0  2  5]
   [ 5  3  1]]

  [[ 0  2  0]
   [-1 10  0]]

  [[ 0  5  1]
   [ 1  7  0]]

  [[ 3  8  7]
   [ 2  3  2]]]


 [[[ 4  5  4]
   [ 3  1  1]]

  [[ 0  2  5]
   [ 0  4  3]]

  [[ 3  2  4]
   [ 5  8  3]]

  [[ 8  2  5]
   [ 2  3  3]]]], shape=(3, 4, 2, 3), dtype=int32)


In [312]:
x = tf.constant(1, shape= (4,4))
print(x)

tf.Tensor(
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]], shape=(4, 4), dtype=int32)


In [313]:
x_np = np.array([3,4,5])
print(x_np)

[3 4 5]


In [314]:
x_tf = tf.convert_to_tensor(x_np, dtype = tf.float16)
print(x_tf)

tf.Tensor([3. 4. 5.], shape=(3,), dtype=float16)


In [315]:
identity_matrix = tf.eye(4, batch_shape=[2], dtype=tf.dtypes.float32, name=None)
print(identity_matrix)

tf.Tensor(
[[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]], shape=(2, 4, 4), dtype=float32)


In [316]:
filled_tensor = tf.fill([4,3], 1., )
print(filled_tensor)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(4, 3), dtype=float32)


In [317]:
ones_tensor = tf.ones([4,3], dtype = tf.float32)
print(ones_tensor)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(4, 3), dtype=float32)


In [318]:
zeros_tensor = tf.zeros([4,3], dtype = tf.float32)
print(zeros_tensor)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(4, 3), dtype=float32)


In [319]:
ones_like_tensor = tf.ones_like(tensor_four_d)
print(ones_like_tensor)
print(tensor_four_d.shape)

tf.Tensor(
[[[[1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]]]


 [[[1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]]]


 [[[1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]]]], shape=(3, 4, 2, 3), dtype=int32)
(3, 4, 2, 3)


In [320]:
normal_tensor = tf.random_normal_initializer(
    mean=0.0, stddev=0.05, seed=None
)

In [321]:
print(normal_tensor)

In [322]:
range_tensor = tf.range(start = 2, limit = 10, delta = 3)
print(range_tensor)

tf.Tensor([2 5 8], shape=(3,), dtype=int32)


In [323]:
print(tf.shape(tensor_three_d,))
print(tensor_three_d.shape)

tf.Tensor([4 2 3], shape=(3,), dtype=int32)
(4, 2, 3)


In [324]:
print(tf.size(tensor_four_d))

tf.Tensor(72, shape=(), dtype=int32)


In [325]:
g = tf.random.Generator.from_non_deterministic_state()
g.normal(shape=(2,), mean = 100, stddev = 1)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([99.74168, 99.83146], dtype=float32)>

In [326]:
g = tf.random.Generator.from_non_deterministic_state()
g.uniform(shape=(2,), minval = 25, maxval = 40)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([33.638016, 33.65309 ], dtype=float32)>

In [327]:
tf.random.normal(
    (3,), mean=0.0, stddev=100.0, dtype=tf.dtypes.float32, seed=12, name="Random Number with Normal distribution"
)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([12.151812,  9.970952, 69.518616], dtype=float32)>

In [328]:
tf.random.uniform(
    (2,), minval=0, maxval=100, dtype=tf.dtypes.float32, seed=None, name=None
)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([20.179546, 34.707115], dtype=float32)>

In [329]:
tensor_indexed = tf.constant([3,6,2,4,6,66,7])
print(tensor_indexed[:])
print(tensor_indexed[0:4])
print(tensor_indexed[3:-3])

tf.Tensor([ 3  6  2  4  6 66  7], shape=(7,), dtype=int32)
tf.Tensor([3 6 2 4], shape=(4,), dtype=int32)
tf.Tensor([4], shape=(1,), dtype=int32)


In [330]:
tensor_two_d = tf.constant([[1,2,0],
                            [3,5,-1],
                            [1,5,6],
                            [2,3,8]])
print(tensor_two_d[...,1])

tf.Tensor([2 5 5 3], shape=(4,), dtype=int32)


In [331]:
tensor_three_d = tf.constant([


                              [[1,2,0],
                               [3,5,-1]],

                              [[10,2,0],
                               [1,0,2]],

                              [[5,8,0],
                               [2,7,0]],

                              [[2,1,9],
                               [4,-3,32]]


                              ])

print(tensor_three_d[ ... , : , 2])

tf.Tensor(
[[ 0 -1]
 [ 0  2]
 [ 0  0]
 [ 9 32]], shape=(4, 2), dtype=int32)


In [332]:
print(tf.expand_dims(tensor_three_d[ ... , : , 2],-1))

tf.Tensor(
[[[ 0]
  [-1]]

 [[ 0]
  [ 2]]

 [[ 0]
  [ 0]]

 [[ 9]
  [32]]], shape=(4, 2, 1), dtype=int32)


In [333]:
x_abs = tf.constant([-2.25, 3.25])
tf.abs(x_abs)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.25, 3.25], dtype=float32)>

In [334]:
tf.abs(tf.constant(-0.2))

<tf.Tensor: shape=(), dtype=float32, numpy=0.20000000298023224>

In [335]:
x_abs_complex = tf.constant([-2.25 + 4.75j])
tf.abs(x_abs_complex)


<tf.Tensor: shape=(1,), dtype=float64, numpy=array([5.25594901])>

In [336]:
tf.sqrt((-2.25)**2 + 4.75**2)

<tf.Tensor: shape=(), dtype=float32, numpy=5.255949020385742>

In [337]:
x_1 = tf.constant([[5,3,6,6,4,6]], dtype = tf.float32)
x_2 = tf.constant([[7], [5], [3]], dtype = tf.float32)

print(x_1.shape)
print(x_2.shape)
print(tf.math.multiply(x_1, x_2))

(1, 6)
(3, 1)
tf.Tensor(
[[35. 21. 42. 42. 28. 42.]
 [25. 15. 30. 30. 20. 30.]
 [15.  9. 18. 18. 12. 18.]], shape=(3, 6), dtype=float32)


In [338]:
x_argmax = tf.constant([[2, 20, 30, 3, 6],
                        [3, 11, 16, 1, 8],
                        [14, 45, 23, 5, 27]])

print(x_argmax.shape)
print(tf.math.argmin(x_argmax, axis = 1))

(3, 5)
tf.Tensor([0 3 3], shape=(3,), dtype=int64)


In [339]:
x_argmax = tf.constant([200, 120, 130, 3, 6])
print(tf.math.argmax(x_argmax))

tf.Tensor(0, shape=(), dtype=int64)


In [340]:
x_argmax = tf.constant([200, 120, 130, 300, 6])
print(tf.math.argmax(x_argmax))

tf.Tensor(3, shape=(), dtype=int64)


In [341]:
x = tf.constant([[2, 2], [3, 3]])
y = tf.constant([[3, 0], [1, 4]])
tf.pow(x, y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 8,  1],
       [ 3, 81]], dtype=int32)>

In [342]:
tf.pow(tf.constant(2) ,tf.constant(3))

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [343]:
tensor_two_d = tf.constant([[1,-2,0],
                            [3,5,100],
                            [1,5,6],
                            [2,3,8]], dtype = tf.float16)
print(tensor_two_d.shape)

print(tf.math.reduce_std(tensor_two_d, axis=0, keepdims=True, name=None))

(4, 3)
tf.Tensor([[ 0.829  2.861 41.38 ]], shape=(1, 3), dtype=float16)


In [344]:
tf.math.top_k(tensor_two_d, k = 2)

TopKV2(values=<tf.Tensor: shape=(4, 2), dtype=float16, numpy=
array([[  1.,   0.],
       [100.,   5.],
       [  6.,   5.],
       [  8.,   3.]], dtype=float16)>, indices=<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[0, 2],
       [2, 1],
       [2, 1],
       [2, 1]], dtype=int32)>)

In [345]:
x_1 = tf.constant([[1,2,0]])

x_2 = tf.constant([[1,2],
                  [3,5],
                  [4,5]])

x_3 = tf.constant([[1,2,0,2],
                  [3,5,-1,2]])

print(x_1.shape, x_2.shape, x_3.shape, tf.transpose(x_2).shape)
# x_3.T = 4,2
# x_2.T = 2,3
print(tf.transpose(x_3)@tf.transpose(x_2))
tf.linalg.matmul(
    x_3, x_2, transpose_a=True, transpose_b=True, adjoint_a=False, adjoint_b=True,
    a_is_sparse=False, b_is_sparse=False, output_type=None, name=None
)

(1, 3) (3, 2) (2, 4) (2, 3)
tf.Tensor(
[[ 7 18 19]
 [12 31 33]
 [-2 -5 -5]
 [ 6 16 18]], shape=(4, 3), dtype=int32)


ValueError: Only one of `transpose_b` and `adjoint_b` can be True. Received `transpose_b`=True, `adjoint_b`=True.

In [ ]:
x_1@x_2

In [ ]:
tf.transpose(x_2)

In [ ]:
print(x_2)

In [ ]:
x_1 =  tf.constant([[[1,2],
                    [3,5]],

                    [[10,0],
                    [1,2]],

                    [[5,0],
                    [2,0]]])

x_2 = tf.constant([[[5,1,4],
                    [34,15,1]],

                    [[1,2,2],
                    [5,3,2]],

                    [[2,2,3],
                    [1,1,1]]])

print(tf.linalg.matmul(x_1, x_2))

In [ ]:
x_1 =  tf.constant([[0,0],
                    [0,2]])

x_2 = tf.constant([[1,0,0],
                    [0,0,0]])

print(tf.linalg.matmul(x_1, x_2))

In [ ]:
tensor_two_d = tf.constant([[1,-2,0],
                            [3,5,100],
                            [1,5,6],
                            [2,3,8]], dtype = tf.float16)

tensor_out_d = tf.constant([[1,0,0],
                            [0,5,0],
                            [0,0,6],
                            [0,0,0]], dtype = tf.float16)

#### ( m-n <= lower) and ( n-m <= upper)
# m -- rows, n --- columns
tf.linalg.band_part(tensor_two_d, 0, -1)

In [ ]:
tensor_two_d_m_n = tf.constant([[0,-1,-2],
                                [1,0,-1],
                                [2,1,0],
                                [3,2,1]], dtype = tf.float16)

tensor_two_d_n_m = tf.constant([[0,1,2],
                                [-1,0,1],
                                [-2,-1,0],
                                [-3,-2,-1]], dtype = tf.float16)

m = 1, n = 2

In [ ]:
tensor_two_d = tf.constant([[1,-2,0],
                            [3,5,100],
                            [1,5,6]], dtype = tf.float32)

tensor_two_d_inv = tf.linalg.inv(tensor_two_d)

In [ ]:
tensor_two_d@tensor_two_d_inv

In [ ]:
s,u,v = tf.linalg.svd(tensor_two_d)
print(s)
print(u)
print(v)

In [ ]:
tensor_three_d = tf.constant([[[1,2,0],
                             [3,5,-1]],

                            [[10,2,0],
                             [1,0,2]],

                            [[5,8,0],
                             [2,7,0]],

                            [[2,1,9],
                             [4,-3,32]]])
print(tensor_three_d.shape)
x_exp = tf.expand_dims(tensor_three_d, axis = 3)
print(x_exp.shape)
print(tf.squeeze(x_exp, axis = 3))
print(tf.reshape(x_exp, [4,2,3]))

In [ ]:
x = tf.constant([[[2,3,4,5]]])
print(x.shape)
x_expanded = tf.expand_dims(x, axis = 0)
print(x_expanded)

In [ ]:
x_squeezed = tf.squeeze(x_expanded, axis = 0)
for i in range(2):
  x_squeezed = tf.squeeze(x_squeezed, axis = 0)

print(x_squeezed)

In [ ]:
x_reshape = tf.constant([[3,5,6,6],
                         [4,6,-1,2]])

print(tf.reshape(x_reshape, [-1]))
print(tf.reshape(x_reshape, [8]))

In [ ]:
tf.transpose(x_reshape)

In [ ]:
t1 = [[1, 2, 3],
      [4, 5, 6],
      [5, 6, 2],
      [1, 2, 1]]

t2 = [[7, 8, 9],
      [10, 11, 12],
      [0, 0, 2],
      [-1, 5, 2]]

print(tf.constant(t1).shape)
print(tf.constant(t2).shape)

tf.concat([t1, t2], axis = 0)

In [ ]:
tf.stack([t1,t2], axis = 2)

In [ ]:
tf.stack([t1,t2], axis = 0)

In [ ]:
tf.concat([tf.expand_dims(t, axis = 0) for t in [t1,t2]], axis = 0)

1,4,3 - 1,4,3 --> 2,4,3

In [ ]:
t1 = [[1, 2, 3],
      [4, 5, 6],
      [5, 6, 2],
      [1, 2, 1]]

t2 = [[7, 8, 9],
      [10, 11, 12],
      [0, 0, 2],
      [-1, 5, 2]]

#4,3 - 4,3 --> 2,4,3
#4,3 - 4,3 --> 4,2,3
#4,3 - 4,3 --> 4,3,2

In [ ]:
t = tf.constant([[1, 2, 3],
                 [4, 5, 6]])

paddings = tf.constant([[1, 5,],
                        [2, 3]])

tf.pad(t, paddings, "CONSTANT", constant_values = 0)

In [ ]:
params = tf.constant(['p0', 'p1', 'p2', 'p3', 'p4', 'p5'])
print(params.shape)
params[1:3+1]

In [ ]:
tf.gather(params, [0,5,3], axis = 0)

In [ ]:
params = tf.constant([

                      [[0, 1.0, 2.0],
                       [10.0, 11.0, 12.0],
                       [20.0, 21.0, 22.0],
                       [30.0, 31.0, 32.0]],

                      [[3, 1.0,21],
                       [1, 3, 88],
                       [0, 5, 55],
                       [0, 2, 30]]

                      ])
print(params.shape)
tf.gather(params, [2, 0], axis = 1)

In [ ]:
params = tf.constant([[3, 1.0,21],
                       [1, 3, 88],
                       [0, 5, 55],
                       [0, 2, 30]])

print(params.shape)
tf.gather(params, [2, 0], axis = 0)

In [ ]:
indices = [2,1]

params = [['a', 'b'],
          ['c', 'd'],
          ['e', 'f']]

tf.gather_nd(params, indices)

In [ ]:
indices = [[0, 1, 0], [1, 0, 1]]

params = [[['a0', 'b0'],
           ['c0', 'd0']],

          [['a1', 'b1'],
           ['c1', 'd1']]]

tf.gather_nd(params, indices)

In [ ]:
indices = [[[0, 1],
            [1, 0]],

            [[0, 0],
             [1, 1]]]

params = [[['a0', 'b0'],
           ['c0', 'd0']],

          [['a1', 'b1'],
           ['c1', 'd1']]]

tf.gather_nd(params, indices)

In [ ]:
indices = [[[0, 1],
            [1, 0]],

            [[0, 0],
             [1, 1]]]

params = [[['a0', 'b0'],
           ['c0', 'd0']],

          [['a1', 'b1'],
           ['c1', 'd1']]]


tf.gather_nd(params, indices, batch_dims = 1)

In [ ]:
indices = [[0,1],
           [1,0]]

params = [[['a0', 'b0'],
           ['c0', 'd0']],

          [['a1', 'b1'],
           ['c1', 'd1']]]


tf.gather_nd(params, indices, batch_dims = 1)

In [ ]:
tensor_two_d = tf.constant([[1,2,0],
                            [3,5,-1],
                            [1,5,6],
                            [2,3,8]])
print(tensor_two_d)

In [ ]:
tensor_two_d =[[1,2,0],
               [3,],
               [1,5,6,5,6],
               [2,3]]
tensor_ragged = tf.ragged.constant(tensor_two_d)
print(tensor_ragged)

In [ ]:
print(tf.RaggedTensor.from_row_lengths(
    values=[3, 1, 4, 1, 5, 9, 2, 6],
    row_lengths=[4, 0, 3, 1,0]))

In [ ]:
tensor_sparse = tf.sparse.SparseTensor(
    indices = [[1,1],[3,4]], values = [11,56], dense_shape = [5,6]
)

In [ ]:
print(tensor_sparse)

In [ ]:
tf.sparse.to_dense(tensor_sparse)

In [ ]:
tensor_string = tf.constant(["hello", "i am ", "a string"])
print(tensor_string)

In [ ]:
tf.strings.join(tensor_string, separator="+")

In [ ]:
x = tf.constant([1,2])

In [ ]:
x_var = tf.Variable(x, name = 'var1')
print(x_var)

In [ ]:
x_var.assign_add([5,8])

In [ ]:
with tf.device('CPU:0'):
  x_1 = tf.constant([1,3,4])
  x_2 = tf.constant([1])

with tf.device('GPU:0'):
  x_3 = x_1 + x_2

print(x_1, x_1.device)
print(x_2, x_2.device)
print(x_3, x_3.device)

In [ ]:
!wget https://github.com/srihari-humbarwadi/datasets/releases/download/v0.1.0/data.zip

In [ ]:
!unzip /content/data.zip -d /content/dataset

In [ ]:
import tensorflow as tf

In [ ]:
input_var = tf.Variable(initial_value=10.)
with tf.GradientTape() as tape:
  result = tf.square(input_var)
gradient = tape.gradient(result, input_var)

In [ ]:
print(gradient)

In [ ]:
input_const = tf.constant(10.)
with tf.GradientTape() as tape:
  tape.watch(input_const)
  result = tf.square(input_const)
gradient = tape.gradient(result, input_const)

In [ ]:
print(gradient)

In [ ]:
time = tf.Variable(0.)
with tf.GradientTape() as outer_tape:
  with tf.GradientTape() as inner_tape:
    position = 4.9 * time ** 2
  speed = inner_tape.gradient(position, time)
acceleration = outer_tape.gradient(speed, time)

In [ ]:
print(speed)

In [ ]:
print(acceleration)

In [ ]:
tensor_indexed = tf.constant([2,4,9,0,4,5,6,7])
                              0 1 2 3 4 5 6 7

In [ ]:
3:7


tensor_indexed[3:7]  3 ---> 6

In [ ]:
print(tensor_indexed[0:7:1])
print(tensor_indexed[0:7:2])

In [ ]:
tensor_indexed[-1]

In [ ]:
tensor_indexed = tf.constant([[2,3,4,5,6],
                              [9,0,4,2,1],
                              [0,0,1,7,0]])

In [ ]:
tensor_indexed[0:2,2:4]

In [ ]:
tensor_indexed[2,2:4+1]

In [ ]:
print(tensor_indexed[0,...])
print(tensor_indexed[0:1,...])

In [ ]:
tensor_indexed = tf.constant(
                              [[[1,2,0],
                                [3,5,-1]],

                              [[10,2,0],
                               [1,0,2]],

                              [[5,8,0],
                               [2,7,0]],

                              [[2,1,9],
                               [4,-3,32]]])

In [ ]:
print(tensor_indexed.shape)

In [ ]:
tensor_indexed[:,:,2]

In [ ]:
x = tf.constant([2,-1,3,-0.1,0])
print(tf.abs(x))

In [ ]:
x = tf.constant(2+3j)
print(tf.abs(x))

In [ ]:
tf.sqrt(2.**2+3.**2)

In [ ]:
x = tf.constant([2,3,5,7])
y = tf.constant([0,2,4,5])
print(tf.math.divide(x,y))

In [ ]:
x = tf.constant([[2,3,4,5]])
y = tf.constant([[1],[3]])
print(tf.math.maximum(x,y))

In [ ]:
A = tf.constant([2, 20, 30, 3, 6])
tf.math.argmin(A)

In [ ]:
t_argmin = tf.constant([
  [3,1,9,6,5],
  [0,1,7,3,2],
  [1,5,1,2,0],
  [7,3,0,9,0],

])
tf.math.argmin(t_argmin,axis=1)

In [ ]:
x = tf.constant([[2, 2], [3, 3]])
y = tf.constant([[0, 1], [2, 3]])
tf.pow(x, y)  # [[256, 65536], [9, 27]]

In [ ]:
input_tensor = tf.constant([
  [3,1,9,6,5],
  [0,1,7,3,2],
  [1,5,1,2,0],
  [7,3,0,9,0],

])
print(tf.math.reduce_sum(
    input_tensor, axis=1, keepdims=True,
))


In [ ]:
result = tf.math.top_k([1, 2, 98, 1, 1, 99, 3, 1, 3, 96, 4, 1],
                        k=1)
print(result)

In [ ]:
x = tf.constant([-50,-5e10, 1.0, 50.0, 100.0])
tf.math.sigmoid(x)

In [ ]:
a = tf.constant([
  [1,5,1],
  [7,3,0],

])

b = tf.constant([
  [3,1],
  [0,1],
  [1,5],

])
print(a.shape, b.shape)
print(tf.linalg.matmul(a,b))
#print(a*b)

In [ ]:
a@b

In [ ]:
a = tf.constant([
  [1,5,1],

])
print(a.shape,tf.transpose(a))

In [ ]:
a = tf.constant([
  [1,5,1],
])

b = tf.constant([
  [3,1],
  [0,1],
  [1,5],
])

print(a.shape, b.shape, tf.linalg.matrix_transpose(b).shape)

In [ ]:
a@b

In [ ]:
tf.linalg.matmul(a,b, transpose_b=True)

In [ ]:
a = tf.constant(
            [[[1,2],
              [3,5]],

            [[10,2],
              [1,0]],

            [[5,8],
              [2,7]],

            [[2,1],
              [4,-3]]])


b = tf.constant(
            [[[1,2,0],
              [3,5,-1]],

            [[10,2,0],
              [1,0,2]],

            [[5,8,0],
              [2,7,0]],

            [[2,1,9],
              [4,-3,32]]])


In [ ]:
print(a.shape,b.shape)

In [ ]:
print(tf.linalg.matmul(a,b))

In [ ]:
print(a[0],b[0])

In [ ]:
a[2]@b[2]

In [ ]:
a = tf.constant([
  [1,5,1],
  [7,9,3],
  [1,3,1],
])
m=n

In [ ]:
m=0, n=1  m-n=-1 n-m=1
      False              True                   False              False
              True                                      False
                                   False
(num_lower < 0 || (m-n) <= num_lower)) && (num_upper < 0 || (n-m) <= num_upper).

In [ ]:
print(a)
print(tf.linalg.band_part(a, 0, -1))# ==> Upper triangular part.
print(tf.linalg.band_part(a, -1, 0))# ==> Lower triangular part.
print(tf.linalg.band_part(a, 0, 0))# ==> Diagonal.

In [ ]:
a = tf.constant([
    [2,6,5,2],
    [2,-2,2,3],
    [1,5,4,0]
])
b = tf.constant([
    [2,9,0,3,0],
    [3,6,8,-2,2],
    [1,3,5,0,1],
    [3,0,2,0,5]
])
c = tf.linalg.matmul(a,b)
print(a.shape,b.shape)
print(c.shape)
print(c)

In [ ]:
tf.einsum("ij,jk->ik",a,b)

In [ ]:
a = tf.constant([2,6,5,2])
b = tf.constant([0,1,3,2])
tf.einsum("i,j->",a,b)

In [ ]:
a = tf.constant([2,6,5,2])
b = tf.constant([0,1,3,2])
c = tf.einsum("i,j->ij",a,b)
print(c)
print(tf.reduce_sum(c))

print(tf.einsum("i,j->",a,b))

In [ ]:
b = tf.constant([
    [2,9,0,3,0],
    [3,6,8,-2,2],
    [1,3,5,0,1],
    [3,0,2,0,5]
])
tf.einsum("ij->ji",b)

In [ ]:
a = tf.constant([
    [2,6,5,2],
    [2,-2,2,3],
    [1,5,4,0]
])
b = tf.constant([
    [2,9,0,3],
    [3,6,8,-2],
    [1,3,5,0],
])
tf.einsum("ij,ij->ij",a,b)

In [ ]:
a*b

In [ ]:
a = tf.constant([

    [[2,6,5,2],
     [2,-2,2,3],
     [1,5,4,0]],

    [[2,6,5,2],
     [2,-2,2,3],
     [1,5,4,0]]
    ])
b = tf.constant([
    [[2,9,0,3,0],
     [3,6,8,-2,2],
     [1,3,5,0,1],
     [3,0,2,0,5]],

    [[2,9,0,3,0],
     [3,6,8,-2,2],
     [1,3,5,0,1],
     [3,0,2,0,5]]
])

In [ ]:
print(a.shape,b.shape)

In [ ]:
tf.einsum("bij,bjk->bik",a,b)

In [ ]:
a = tf.constant([

    [[2,6,5,2],
     [2,-2,2,3],
     [1,5,4,0]],

    [[2,6,5,2],
     [2,-2,2,3],
     [1,5,4,0]]
    ])

print(tf.linalg.matmul(a,a,transpose_b=True))
print(a.shape)

In [ ]:
2,3,4 @ transpose(2,30,4 )
2,3,4 @ (2,4,30)

In [ ]:
print(tf.einsum("bij,bkj->bik",a,a))

In [ ]:
a = tf.constant([1,3,4,5,6,7])
print(a.shape)

In [ ]:
tf.expand_dims(a,axis=0)

In [ ]:
tf.expand_dims(a,axis=1)

In [ ]:
a = tf.constant([

    [[2,6,5,2],
     [2,-2,2,3],
     [1,5,4,0]],

    [[2,6,5,2],
     [2,-2,2,3],
     [1,5,4,0]]
    ])
print(a.shape)
1,2,3,4

In [ ]:
c = tf.expand_dims(a,axis=-1)
print(c.shape)
print(tf.squeeze(c,axis=-1))

In [ ]:
a = tf.constant([1,2,3,4,5,6,7,8,9])
print(tf.reshape(a,[3,-1,1]))

In [ ]:
t1 = tf.constant(
    [[1, 4, 3],
      [2, 5, 6]])
print(t1.shape)

In [ ]:
tf.reshape(t1,[6])

In [ ]:
t1 = tf.constant(
    [[1, 2, 3],
     [4, 5, 6]])

t2 = tf.constant(
    [[7, 8, 9],
     [10, 11, 12]])
print(t1.shape, t2.shape)

In [ ]:
tf.concat([tf.expand_dims(t1,-1),
          tf.expand_dims(t2,-1)],axis=-1)

In [ ]:
tf.stack([t1,t2],axis=-1)

In [ ]:
tf.concat([t1,t2],axis=0)

In [ ]:
t1 = tf.constant([
    [[1, 2],
     [2, 3]],

    [[4, 4],
     [5, 3]]
])
t2 = tf.constant([
    [[7, 4],
     [8, 4]],

    [[2, 10],
     [15, 11]]
])
print(t1.shape,t2.shape)


In [ ]:
(2, 2, 2) (2, 2, 2) ---> (4,2,2)

In [ ]:
print(tf.concat([t1, t2], 0))

In [ ]:
t = tf.constant([[1, 2, 3],
                 [4, 5, 6]])
paddings = tf.constant([[4, 1,],
                        [2, 4]])
# 'constant_values' is 0.
# rank of 't' is 2.
print(tf.pad(t, paddings, "CONSTANT", constant_values=9))

In [ ]:
a = tf.constant([4,5,6,7])
print(a[1:3])

In [ ]:
tf.gather(a,[0,3,1],axis=0)

In [ ]:
b = tf.constant([
    [2,9,0,3,0],
    [3,6,8,-2,2],
    [1,3,5,0,1],
    [3,0,2,0,5]
])

In [ ]:
tf.gather_nd(b,[[1],
                [3]])

In [ ]:
tf.gather(b,[1,3],axis=0)

In [ ]:
tf.gather(b,[[1,3],
             [2,0]],axis=0)

In [ ]:
a = tf.ragged.constant([
    [1,3],
    [4,5,6],
    [7]
])
print(a)

In [ ]:
tf.ragged.boolean_mask(  # Mask a 2D RaggedTensor.
    tf.ragged.constant([[1, 2, 3], [4], [5, 6]]),
    tf.ragged.constant([[False, False, True], [False], [True, True]])).to_list()

In [ ]:
values = [3, 1, 4, 1, 5, 9, 2, 6,7]


print(tf.RaggedTensor.from_uniform_row_length(values, uniform_row_length=3))


In [ ]:
sparse_tensor = tf.sparse.SparseTensor(
    indices=[[0, 0],
             [2, 5]], values=[5, 9], dense_shape=[5,6])

In [ ]:
sparse_tensor

In [ ]:
tf.sparse.to_dense(sparse_tensor)

In [ ]:
tensor_string_1 = tf.constant(["i am ", "a", "string"])
tensor_string_2 = tf.constant(["i am ", "not a", "string"])

In [ ]:
tf.strings.join([tensor_string_1,tensor_string_2], separator="+")

In [ ]:
x = tf.constant([1,2,3,4,5])

In [ ]:
x_var = tf.Variable(x)

In [ ]:
print(x,x_var)

In [ ]:
x_var.assign_sub([5,5,5,5,5])

In [ ]:
x_var.assign([5,5,5,5,5])